POST http://localhost:4000/api/client HTTP/1.1
content-type: application/json

{
    "username": "sampleuser",
    "email": "faizan@gmail.com",
    "password": "12345"
}

###
# GET http://localhost:4000/api/client HTTP/1.1
###
# GET http://localhost:4000/api/client/1 HTTP/1.1


###
POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "shani@gmail.com",
    "password": "12345"
}
###
POST http://localhost:4000/api/auth/register HTTP/1.1
content-type: application/json

{
    "company":"Webeasy1",
    "firstname": "shani",
    "lastname": "bhatti",
    "username":"shani.bhatti",
    "email": "shani@gmail.com",
    "addressline1":"street 5",
    "addressline2":"MDK",
    "addressline3":"MDK",
    "city":"SKP",
    "state":"punjab",
    "zipcode":"78786",
    "phonenumber":"03204033575"
}

###
POST http://localhost:4000/api/auth/passwordset HTTP/1.1
content-type: application/json

{
    "email":"shani@gmail.com",
    "password":"12345"
}

###
POST   http://localhost:4000/api/auth/forgotpassword HTTP/1.1
Content-type: application/json

{
   "password":"abcd@gmail.com"
}

###
POST   http://localhost:4000/api/auth/jwttoken HTTP/1.1
Content-type: application/json

{

}

###
POST   http://localhost:4000/api/middleware/upload HTTP/1.1
Content-type: application/json

{

}

###
GET   http://localhost:4000/api/files HTTP/1.1
Content-type: application/json

{

}

###
GET   http://localhost:4000/api/files/ HTTP/1.1
Content-type: application/json

{

}
