POST http://localhost:4000/api/client HTTP/1.1
content-type: application/json

{
    "username": "sampleuser",
    "email": "faizan@gmail.com",
    "password": "12345"
}

###
# GET http://localhost:4000/api/client HTTP/1.1
###
# GET http://localhost:4000/api/client/1 HTTP/1.1


###
POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "username": "Ali7864",
    "password": "1234"
}
###
POST http://localhost:4000/api/auth/register HTTP/1.1
content-type: application/json

{
    "company":"Webeasy1",
    "firstname": "Ali",
    "lastname": "Ahmad",
    "username":"Ali7864",
    "email": "abcd@gmail.com",
    "addressline1":"street 5",
    "addressline2":"MDK",
    "addressline3":"MDK",
    "city":"SKP",
    "state":"punjab",
    "zipcode":"78786",
    "phonenumber":"03198734278"
}

###
POST http://localhost:4000/api/auth/passwordset HTTP/1.1
content-type: application/json

{
    "username":"Ali7864",
    "password":"1234"
}

###
POST   http://localhost:4000/api/auth/forgotpassword HTTP/1.1
Content-type: application/json

{
   "password":"abcd@gmail.com"
}

###
POST   http://localhost:4000/api/auth/jwttoken HTTP/1.1
Content-type: application/json

{

}